on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    with:
      composer-command: |
        composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        php -S 127.0.0.1:8080 -t tests/_data/public > /dev/null 2>&1 &
      extensions: fileinfo, intl, pdo, pdo_sqlite
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2']
